# Generated by Django 2.2 on 2021-08-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals_users_app', '0002_auto_20210804_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dreamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams_made', to='goals_users_app.User')),
                ('users_who_dream', models.ManyToManyField(related_name='dreams_acheived', to='goals_users_app.User')),
            ],
        ),
    ]
