# Generated by Django 2.2 on 2021-08-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_users_app', '0003_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_goals', to='goals_users_app.User'),
        ),
    ]
